apiVersion: v1
kind: Service
metadata:
  name: endo-service
  namespace: mhealth
spec:
  selector:
    app: endo-mhealth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP